obj-m += monitor.o

all:
	gcc -o engine engine.c
	gcc -o cpu_hog cpu_hog.c
	gcc -o memory_hog memory_hog.c
	gcc -o io_pulse io_pulse.c
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

ci:
	gcc -o engine engine.c

clean:
	rm -f engine cpu_hog memory_hog io_pulse
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
